source 'https://rubygems.org'



gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass', '~> 3.3.3'
gem 'autoprefixer-rails'
gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-bootstrap'
gem 'ai4r'
gem 'lazy_high_charts'




group :development, :test do
  
  gem 'byebug'

  
  gem 'web-console', '~> 2.0'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

